services:
  - type: web
    name: my-telegram-bot
    env: python
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: TOKEN
        value: 7823143146:AAGoasXtZY1H2-fDrrQUN-dEMW6xWcYqTeU
